In [1]:
import numpy as np
import pandas as pd

In [2]:
df_can = pd.read_excel('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DV0101EN/labs/Data_Files/Canada.xlsx',
                       sheet_name='Canada by Citizenship',
                       skiprows=range(20),
                       skipfooter=2)

In [3]:
df_can.head(5)

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

In [4]:
df_can.tail(5)

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407

In [5]:
df_can.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 43 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Type      195 non-null    object
 1   Coverage  195 non-null    object
 2   OdName    195 non-null    object
 3   AREA      195 non-null    int64
 4   AreaName  195 non-null    object
 5   REG       195 non-null    int64
 6   RegName   195 non-null    object
 7   DEV       195 non-null    int64
 8   DevName   195 non-null    object
 9   1980      195 non-null    int64
 10  1981      195 non-null    int64
 11  1982      195 non-null    int64
 12  1983      195 non-null    int64
 13  1984      195 non-null    int64
 14  1985      195 non-null    int64
 15  1986      195 non-null    int64
 16  1987      195 non-null    int64
 17  1988      195 non-null    int64
 18  1989      195 non-null    int64
 19  1990      195 non-null    int64
 20  1991      195 non-null    int64
 21  1992      195 non-null    int64
 22  1993      195 non-null    int64
 23  1994      195 non-null    int64
 24  1995      195 non-null    int64
 25  1996      195 non-null    int64
 26  1997      195 non-null    int64
 27  1998      195 non-null    int64
 28  1999      195 non-null    int64
 29  2000      195 non-null    int64
 30  2001      195 non-null    int64
 31  2002      195 non-null    int64
 32  2003      195 non-null    int64
 33  2004      195 non-null    int64
 34  2005      195 non-null    int64
 35  2006      195 non-null    int64
 36  2007      195 non-null    int64
 37  2008      195 non-null    int64
 38  2009      195 non-null    int64
 39  2010      195 non-null    int64
 40  2011      195 non-null    int64
 41  2012      195 non-null    int64
 42  2013      195 non-null    int64
dtypes: int64(37), object(6)
memory usage: 65.6+ KB

In [6]:
df_can.columns.values

array(['Type', 'Coverage', 'OdName', 'AREA', 'AreaName', 'REG', 'RegName',
       'DEV', 'DevName', 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013], dtype=object)

In [7]:
df_can.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194],
      dtype=int64)

In [9]:
print(type(df_can.columns))
print(type(df_can.index))

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.range.RangeIndex'>

In [16]:
df_can.columns.tolist()
print(type(df_can.columns.tolist()))

<class 'list'>

In [20]:
con = df_can["AreaName"]=="Africa"

In [22]:
print(con)

0      False
1      False
2       True
3      False
4      False
       ...
190    False
191     True
192    False
193     True
194     True
Name: AreaName, Length: 195, dtype: bool

In [25]:
df_can[con].head(6)

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
5,Immigrants,Foreigners,Angola,903,Africa,911,Middle Africa,902,Developing regions,1,...,268,295,184,106,76,62,61,39,70,45
19,Immigrants,Foreigners,Benin,903,Africa,914,Western Africa,902,Developing regions,2,...,112,95,116,183,205,238,290,284,391,397
23,Immigrants,Foreigners,Botswana,903,Africa,913,Southern Africa,902,Developing regions,10,...,9,7,11,8,28,15,42,53,64,76
27,Immigrants,Foreigners,Burkina Faso,903,Africa,914,Western Africa,902,Developing regions,2,...,97,91,147,136,139,162,186,144,269,322
28,Immigrants,Foreigners,Burundi,903,Africa,910,Eastern Africa,902,Developing regions,0,...,559,626,468,614,448,566,529,604,684,480

In [26]:
kosul1 = df_can["RegName"]=="Southern Europe"

In [27]:
df_can[kosul1]

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1
22,Immigrants,Foreigners,Bosnia and Herzegovina,908,Europe,925,Southern Europe,901,Developed regions,0,...,188,211,217,209,182,156,168,140,121,119
44,Immigrants,Foreigners,Croatia,908,Europe,925,Southern Europe,901,Developed regions,0,...,151,128,102,102,131,92,91,135,112,125
69,Immigrants,Foreigners,Greece,908,Europe,925,Southern Europe,901,Developed regions,1065,...,120,100,74,110,107,119,101,102,146,298
85,Immigrants,Foreigners,Italy,908,Europe,925,Southern Europe,901,Developed regions,1820,...,334,344,325,320,370,429,434,374,440,545
108,Immigrants,Foreigners,Malta,908,Europe,925,Southern Europe,901,Developed regions,191,...,28,28,24,7,21,18,17,8,9,4
115,Immigrants,Foreigners,Montenegro,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,0,7,19,10,14,19,26,9
138,Immigrants,Foreigners,Portugal,908,Europe,925,Southern Europe,901,Developed regions,4473,...,336,338,424,405,665,623,629,528,560,630
149,Immigrants,Foreigners,San Marino,908,Europe,925,Southern Europe,901,Developed regions,1,...,0,0,0,0,0,0,1,0,0,0
153,Immigrants,Foreigners,Serbia,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,3,50,259,365,271,299,395,297
158,Immigrants,Foreigners,Slovenia,908,Europe,925,Southern Europe,901,Developed regions,0,...,17,23,11,29,18,27,12,13,36,20
161,Immigrants,Foreigners,Spain,908,Europe,925,Southern Europe,901,Developed regions,211,...,133,126,124,137,169,195,174,179,262,331
172,Immigrants,Foreigners,The former Yugoslav Republic of Macedonia,908,Europe,925,Southern Europe,901,Developed regions,0,...,443,285,256,211,191,198,188,130,126,112

In [44]:
df_can[(df_can["AreaName"]=="Europe") & (df_can["RegName"] == "Southern Europe")]

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1
22,Immigrants,Foreigners,Bosnia and Herzegovina,908,Europe,925,Southern Europe,901,Developed regions,0,...,188,211,217,209,182,156,168,140,121,119
44,Immigrants,Foreigners,Croatia,908,Europe,925,Southern Europe,901,Developed regions,0,...,151,128,102,102,131,92,91,135,112,125
69,Immigrants,Foreigners,Greece,908,Europe,925,Southern Europe,901,Developed regions,1065,...,120,100,74,110,107,119,101,102,146,298
85,Immigrants,Foreigners,Italy,908,Europe,925,Southern Europe,901,Developed regions,1820,...,334,344,325,320,370,429,434,374,440,545
108,Immigrants,Foreigners,Malta,908,Europe,925,Southern Europe,901,Developed regions,191,...,28,28,24,7,21,18,17,8,9,4
115,Immigrants,Foreigners,Montenegro,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,0,7,19,10,14,19,26,9
138,Immigrants,Foreigners,Portugal,908,Europe,925,Southern Europe,901,Developed regions,4473,...,336,338,424,405,665,623,629,528,560,630
149,Immigrants,Foreigners,San Marino,908,Europe,925,Southern Europe,901,Developed regions,1,...,0,0,0,0,0,0,1,0,0,0
153,Immigrants,Foreigners,Serbia,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,3,50,259,365,271,299,395,297
158,Immigrants,Foreigners,Slovenia,908,Europe,925,Southern Europe,901,Developed regions,0,...,17,23,11,29,18,27,12,13,36,20
161,Immigrants,Foreigners,Spain,908,Europe,925,Southern Europe,901,Developed regions,211,...,133,126,124,137,169,195,174,179,262,331
172,Immigrants,Foreigners,The former Yugoslav Republic of Macedonia,908,Europe,925,Southern Europe,901,Developed regions,0,...,443,285,256,211,191,198,188,130,126,112